project:
  type: website
  output-dir: docs

website:
  title: "Michael Luu, MPH"
  navbar:
    right:
      - blog.qmd
      - publications.qmd
      - presentations.qmd
      - icon: github
        href: https://github.com/mluu921
      - icon: linkedin
        href: https://www.linkedin.com/in/miluu/
format:
  html:
    theme: cosmo
    css: styles.css



