---
title: "Publications"
date-modified: today
echo: false
warning: false
message: false
title-block-banner: false
page-layout: article
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(RefManageR)
library(gt)

q <- '(Michael Luu) AND (Cedars-Sinai[Affiliation])'

last_refreshed <- fs::file_info('publications.bib') |> pull(modification_time) |> date()

if(last_refreshed < Sys.Date()) {
  
  data <- RefManageR::ReadPubMed(q, retmax = 999)
  
  RefManageR::WriteBib(data, file = 'publications.bib')
  
}

data <- RefManageR::ReadBib('publications.bib')

data <- data |> as_tibble()

```

Complete bib file can be downloaded [here](https://github.com/mluu921/mluu921.github.io/blob/master/publications.bib).

```{r}
#| column: screen-inset

tbl <- data |>
  select(title, author, year, month, journal, doi) |>
  transmute(date = mdy(paste0(month, '-', year)),
            title, author, journal, doi) |> 
  arrange(desc(date))

tbl <- tbl |> 
  mutate(
    author = str_replace_all(author, ' and ', ', '),
    author = str_replace_all(author, 'Michael Luu', '**Michael Luu**'),
    doi = glue::glue('https://doi.org/{doi}'),
    title = glue::glue('<a href={doi}>{title}</a>')
  ) |> 
  select(-doi)

tbl |> 
  gt() |> 
  cols_label(
    date = 'Date',
    title = 'Title',
    author = 'Authors',
    journal = 'Journal'
  ) |> 
  opt_interactive(
    use_search = TRUE,
    use_filters = TRUE,
    use_resizers = TRUE,
    use_highlight = TRUE,
    use_compact_mode = TRUE,
    use_text_wrapping = TRUE,
    use_page_size_select = TRUE,
    page_size_default = 25
  ) |> 
  fmt_markdown(columns = author) |> 
  fmt_date(columns = date,
           date_style = 'yMMM') |> 
  fmt_url(columns = title) |> 
  cols_align(columns = title, align = 'left') |> 
  cols_width(
    title ~ px(500),
    date ~ px(100)
  ) |> 
  tab_options(
    heading.title.font.size = 30,
    heading.title.font.weight = 'bold'
  )
```
